DROP TABLE IF EXISTS person;

CREATE TABLE person
(
    id               INTEGER generated by default as identity ,
    first_name        VARCHAR                           NOT NULL,
    last_name          VARCHAR                           NOT NULL,
    middle_name        VARCHAR                           NOT NULL

);

insert into  person (first_name, last_name, middle_name)
            values ('Авдеев', 'Александр', 'Александрович'),
                    ('Адучиев', 'Батор' ,'Канурович'),
                   ('Азимов', 'Рахим', 'Азизбоевич'),
                   ('Аксаков', 'Анатолий', 'Геннадьевич'),
                   ('Алексеева', 'Татьяна', 'Олеговна'),
                   ('Алимова', 'Ольга', 'Николаевна'),
                   ('Альшевских', 'Андрей', 'Геннадьевич'),
                   ('Ананских', 'Игорь', 'Александрович'),
                   ('Андрейченко', 'Андрей', 'Валерьевич')